config/routes.rb
Rails.application.routes.draw do

  resources :complaints
  root 'complaints#index'

end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
   validates :to, presence: true, length: { minimum: 3 }
   validates :text, presence: true, length: { minimum: 3 }
   validates :from, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  def index
    @complaints = Complaint.page(params[:page]).order('created_at DESC')
  end

  def show
    @complaint = Complaint.find(params[:id])
  end

  def new
    @complaint = Complaint.new
  end

  def create
    @complaint = Complaint.new(complaint_params)

    if @complaint.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

private
  def complaint_params
    params.require(:complaint).permit(:to, :text, :from)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/complaints/index.html.erb
<div class="container">
  <h1>The Complaints Department</h1>

  <div class="row">
    <div class="col s12">
      <%= link_to 'Make a Complaint', new_complaint_path, class:"waves-effect waves-light btn red darken-4"  %>
    </div>
  </div>

  <div class="row">
    <h2>Complaints</h2>
    <table class="responsive-table">
      <tr>
        <th>To</th>
        <th>Complaint</th>
        <th>From</th>
      </tr>

      <% @complaints.each do |complaint| %>
        <tr>
          <td><%= complaint.to %></td>
          <td><%= complaint.text %></td>
          <td><%= complaint.from %></td>
        </tr>
      <% end %>
    </table>

    <%= will_paginate @complaints %>
  </div>
</div>

app/views/complaints/new.html.erb
<div class="container">

  <h1>Complain About Something</h1>
  <div class="row">
    <div class="col s12">
      <%= form_for :complaint, url: complaints_path do |f| %>
        <% if @complaint.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@complaint.errors.count, "error") %> prohibited
              this complaint from being saved:
            </h2>
            <ul>
              <% @complaint.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <p>
          <%= f.label "Who is the Complaint about?" %><br>
          <%= f.text_field :to %>
        </p>

        <p>
          <%= f.label "What is your complaint?" %><br>
          <%= f.text_area :text %>
        </p>

        <p>
          <%= f.label "Who are you?" %><br>
          <%= f.text_field :from %>
        </p>

        <p>
          <%= f.submit "Complain", class: "waves-effect waves-light btn red darken-4" %>
        </p>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <%= link_to 'Back', complaints_path, class:"waves-effect waves-light btn blue darken-4" %>
    </div>
  </div>
</div>

app/views/complaints/show.html.erb
<p>
  <strong>To</strong>
  <%= @complaint.to %>
</p>

<p>
  <strong>Complaint</strong>
  <%= @complaint.text %>
</p>

<p>
  <strong>From</strong>
  <%= @complaint.from %>
</p>

<%= link_to 'Complaints', complaints_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComplaintsDepartment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>